### ISSUE TITLE
Compare with github.com/flynn/go-shlex

### ISSUE THREAD

**Issue by ahmetb** [anmitsu/go-shlex#1]
Could you please compare this with https://godoc.org/github.com/flynn/go-shlex ?

Is there a reason why people should prefer Google's go-shlex over yours or vice versa?
# question

**Comment by progrium** [comment]
flynn/go-shlex (now unmaintained) was a fork of google/go-shlex because google/go-shlex was missing support for a bunch of characters and seemed to be unmaintained. This repo looks like it was started from scratch and hopefully doesn't have the same problem of being overly pedantic.

**Comment by anmitsu** [comment]
Please see:
https://godoc.org/github.com/anmitsu/go-shlex#example-Split--CompareFlynn
