### ISSUE TITLE
example pulling github.com/flynn/go-shlex

### ISSUE THREAD

**Issue by orgrim** [anmitsu/go-shlex#4]
Hello,

By using your module, I've found that `github.com/flynn/go-shlex` gets pulled as dependency. It is because it is used in the `example_test.go` file, but not required.

Would putting it in a examples/ subdirectory and updating go.mod avoid that?

Thanks and regards

**Comment by anmitsu** [comment]
I also think  module dependency for comparative example is not desirable.

And because `github.com/flynn/go-shlex` is not updated for a long time, I remove this pkg.
